FROM mysql:latest

# Creds needed for intialization
ENV MYSQL_ROOT_PASSWORD=${DB_USER}
ENV MYSQL_USER=${DB_USER}
ENV MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

RUN apt update -y && apt install -y git

RUN mkdir -p /home/data && \
    git clone https://github.com/bobbybabu007/nodejs-express-Swagger-api-mysql.git /home/data/ && \
    chown -R root:root /home/data/ 

# Adding the automation scripts for Database Setup
RUN cp /home/data/setup-titanic.sql /docker-entrypoint-initdb.d/ && \
    cp /home/data/train-titanic.sql /docker-entrypoint-initdb.d/

# COPY ./setup-titanic.sql /docker-entrypoint-initdb.d/
# COPY ./train-titanic.sql /docker-entrypoint-initdb.d/